config/routes.rb
ForestListaker::Application.routes.draw do
  resources :list_items
  
  resources :lists

  get "dashboard/index"

  root 'dashboard#index'

end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :list_items
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  belongs_to :list
  acts_as_list scope: :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_nav_lists

  def set_nav_lists
  	@nav_lists = List.all
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: [:show, :edit, :update, :destroy]

  # GET /list_items
  # GET /list_items.json
  def index
    @list_items = ListItem.all
  end

  # GET /list_items/1
  # GET /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items
  # POST /list_items.json
  def create
    @list_item = ListItem.new(list_item_params)

    respond_to do |format|
      if @list_item.save
        format.html { redirect_to @list_item, notice: 'List item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1
  # PATCH/PUT /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to @list_item, notice: 'List item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1
  # DELETE /list_items/1.json
  def destroy
    @list_item.destroy
    respond_to do |format|
      format.html { redirect_to list_items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_item_params
      params.require(:list_item).permit(:title, :position, :list_id)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render action: 'show', status: :created, location: @list }
      else
        format.html { render action: 'new' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def app_name
		Rails.application.class.to_s.split("::").first.underscore.humanize.titleize
	end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/dashboard/index.html.haml
%h1 Forest Listaker

%p Custom list making app for site map editing.

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "foundation-rails"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tags
  %body
    = render "shared/navigation"
    .row
      = yield
    = javascript_include_tag "application"

app/views/list_items/_form.html.haml
= form_for @list_item do |f|
  - if @list_item.errors.any?
    #error_explanation
      %h2= "#{pluralize(@list_item.errors.count, "error")} prohibited this list_item from being saved:"
      %ul
        - @list_item.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :list
    = f.collection_select(:list_id, List.all, :id, :title)
  .actions
    = f.submit 'Save'

app/views/list_items/edit.html.haml
%h1 Editing list_item

= render 'form'

= link_to 'Show', @list_item
\|
= link_to 'Back', list_items_path

app/views/list_items/index.html.haml
%h1 Listing list_items

%table
  %tr
    %th Title
    %th Position
    %th List
    %th
    %th
    %th

  - @list_items.each do |list_item|
    %tr
      %td= list_item.title
      %td= list_item.position
      %td= list_item.list.title
      %td= link_to 'Show', list_item
      %td= link_to 'Edit', edit_list_item_path(list_item)
      %td= link_to 'Destroy', list_item, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New List item', new_list_item_path

app/views/list_items/new.html.haml
%h1 New list_item

= render 'form'

= link_to 'Back', list_items_path

app/views/list_items/new.js.erb
$("#new_list_item_link").hide().after('<%= j render("/list_items/form") %>');

app/views/list_items/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @list_item.title
%p
  %b Position:
  = @list_item.position
%p
  %b List:
  = @list_item.list.title

= link_to 'Edit', edit_list_item_path(@list_item)
\|
= link_to 'Back', list_items_path

app/views/lists/_form.html.haml
= form_for @list do |f|
  - if @list.errors.any?
    #error_explanation
      %h2= "#{pluralize(@list.errors.count, "error")} prohibited this list from being saved:"
      %ul
        - @list.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'

= link_to 'Show', @list
\|
= link_to 'Back', lists_path

app/views/lists/index.html.haml
%h1 Listing lists

%table
  %tr
    %th Title
    %th
    %th
    %th

  - @lists.each do |list|
    %tr
      %td= list.title
      %td= link_to 'Show', list
      %td= link_to 'Edit', edit_list_path(list)
      %td= link_to 'Destroy', list, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New List', new_list_path

app/views/lists/new.html.haml
%h1 New list

= render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.haml
%p#notice= notice

%p
	%b Title:
	= @list.title

%p 
	= link_to "New Item", new_list_item_path, remote: true, id: 'new_list_item_link'

%ul 
	- @list.list_items.each do |list_item|
		%li= link_to list_item.title, list_item

= link_to 'Edit', edit_list_path(@list)
\|
= link_to 'Back', lists_path

app/views/shared/_navigation.html.haml
%nav.top-bar{"data-topbar" => ""}
  %ul.title-area
    %li.name
      %h1
        = link_to app_name, root_path
    %li.toggle-topbar.menu-icon
      %a{href: "#"}
        %span Menu
  %section.top-bar-section
    / Left Nav Section
    %ul.left
      %li{class: ('has-dropdown' if @nav_lists.size > 0)}
        = link_to "Lists", lists_path
        - if @nav_lists.size > 0
          %ul.dropdown
            - @nav_lists.each do |list|
              %li= link_to list.title, list